### ISSUE TITLE
AcquireTokenForClient Stuck when application hosted in IIS

### ISSUE THREAD

**Issue by TejendraPrasad** [AzureAD/microsoft-authentication-extensions-for-dotnet#142] opened 2021-03-31 21:02 UTC
Hi,

I am trying to acquire Token using certificate to connect Graph API. Its works in console application and local IIS express.

However, when hosted same in IIS it get stuck and timed out.

Code Snippet:

               var msalClient = ConfidentialClientApplicationBuilder
                .Create(config.ClientID)
                .WithCertificate(GetCertificateByThumbprint(config.ApplicationThumbprint))
                .WithAuthority(AadAuthorityAudience.AzureAdMyOrg, true)
                .WithTenantId(config.TenantID)
                .Build();

             result = await msalClient.AcquireTokenForClient(scopes).ExecuteAsync(); // **Gets Stuck** - IT DOES EVEN GO TO NEXT STEP

            requestMessage.Headers.Authorization =
                new AuthenticationHeaderValue("bearer", await GetAccessTokenAsync());

            var users = await graphClient.Users.Request().Filter($"mail eq '{emailAddress}'").GetAsync();

I have createD ASP.NET MVC for poc and will convert into Web API.

I do not want to use user login token or such... There is no login page and we want to interact MS Graph API using application specific Client ID.

Please some one help on this.

thank you!

**Comment by jmprieur** [comment] 2021-04-05 08:47
@TejendraPrasad : I would think that this is an IIS configuration issue (output ports or something like that)
This works in a console app, which rules out MSAL.NET

**Comment by jmprieur** [comment] 2021-04-05 08:50
Closing as a duplicate of https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2520

**Closed by jmprieur** 2021-04-05 08:50 UTC
Labels: external

**Comment by TejendraPrasad** [comment] 2021-04-05 08:59
thank you @jmprieur  it worked :)

**Comment by jmprieur** [comment] 2021-04-05 09:01
What did you change, @TejendraPrasad  ?

**Comment by TejendraPrasad** [comment] 2021-04-05 09:04
When i executed Application Pool Identity with my Id it worked but it was not working with default application pool Identity.

Then i found it did not know which IP Proxy it has to connect with default

So, i added below config in web.config

`<configuration>  
  <system.net>  
    <defaultProxy>  
      <proxy  
        usesystemdefault="True"  
        proxyaddress=""  
        bypassonlocal="True"  
      />  `
