### ISSUE TITLE
Increase concurrency level to 150+ threads

### ISSUE THREAD

**Issue by yihezkel** [AzureAD/microsoft-authentication-extensions-for-dotnet#110] opened 2020-11-05 08:32 UTC
When multiple threads / two processes use the MsalCacheHelper, it throws the following exception:
System.InvalidOperationException: Could not get access to the shared lock file. ---> System.IO.IOException: The process cannot access the file 'C:\Users\yosefd\AppData\Roaming\Kusto\userTokenCache.data.lockfile' because it is being used by another process.

We experienced this via a command line tool we have. When it runs for enough time, sporadically, authentication pop-ups appear and if not confirmed, the connection fails on timeout. Each time there is a pop-up, we see that exception.

More background about how we’re reproducing the error:
This happened on Windows 10, both when Kusto Explorer (another tool of ours that uses the MsalCacheHeper) was running and also when it was not running. The exception happens in the context of that command-line tool, and not Kusto Explorer. The tool that hits these exceptions was running alone (one process). It had many concurrent threads, about 150, and all were performing remote calls.

**Comment by bgavrilMS** [comment] 2020-11-05 13:33
CC @jmprieur for this important bug

**Comment by jmprieur** [comment] 2020-11-05 14:01
@bgavrilMS can we priortize for next release that will get along with MSAL.NET 4.23.0?

**Comment by bgavrilMS** [comment] 2020-11-05 14:16
@yihezkel - is this a common scenario to have 150 threads do this work? 

We've done some stress testing in the past and found that the current approach fails at around ~10-20 threads on Mac and Linux. We've tested Windows as well but haven't found an upper bound, although we may have not tested with 150 threads. 

Petro had some thoughts on how to improve but I do not know if 150 threads can be achieved.

**Comment by yihezkel** [comment] 2020-11-12 18:03
Quick note - this was discussed offline

**Comment by jmprieur** [comment] 2020-11-30 13:42
@yihezkel : I was not part of the offline conversation. what was discussed/decided? is this still an issue?

**Comment by bgavrilMS** [comment] 2020-11-30 13:54
This is still an issue, and we should fix it at some point by using read locks as well as write locks. I marked it as P2 because the use case is not common - around 150 threads running concurrently. But it is not extreme, since an SDK can be used for parallel calls.

**Comment by bgavrilMS** [comment] 2021-05-18 12:00
This token caching library is meant to be used in public client scenarios, such as desktop clients, which should not exibit this level of concurrency. If you require this level of concurrency I suggest you experiment with using a different syncronization mechanism. When this library was designed, we chose to use file locks because they are ubiquitous and we have not found alternatives that would easily work across the 3 OSes. I do not think this requirements has changed.

**Comment by yihezkel** [comment] 2021-05-21 11:55
I suggest this limitation/assumption be documented. For example, https://github.com/AzureAD/microsoft-authentication-extensions-for-dotnet/wiki/Cross-platform-Token-Cache only says that one of the goals is "Token cache storage can be accessed by multiple processes concurrently.", which is true but with a qualification.

**Comment by bgavrilMS** [comment] 2023-05-18 16:29
We will not be fixing this as most public client use a single / a few thread to get tokens. Nobody else complained about this. 

If Kusto has a complex scenario requiring many threads, I recommend you use MSAL's lower level extensibility to build your own cache, for example an memory cache that periodically saves data a file. 

Or, if you have a solution for fixing the existing one, please contribute. This project is quite simple.

**Closed by bgavrilMS** 2023-05-18 16:29 UTC
Labels: enhancement
